# Generated by Django 2.1 on 2018-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_connect_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后连接ip'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_connect_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后连接时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
