# Generated by Django 2.1 on 2018-08-19 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180819_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorized',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher', verbose_name='教师外键'),
        ),
    ]
