# Generated by Django 2.1 on 2018-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180819_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_connecting',
            field=models.BooleanField(default=False, verbose_name='是否正在连接状态'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_connect_account',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='最后连接的tea账号'),
        ),
    ]
