# Generated by Django 2.1.1 on 2018-10-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='tea账号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_using', models.BooleanField(default=False, verbose_name='是否正在使用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='延时授权码')),
                ('duration', models.IntegerField(default=60, verbose_name='时长')),
                ('available', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, verbose_name='用户登录ip')),
                ('login_time', models.DateTimeField(verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(verbose_name='退出时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='qq账号')),
                ('identity', models.IntegerField(choices=[('0', '超级用户'), ('1', '普通用户'), ('2', 'VIP'), ('3', 'SVIP')], default='1', verbose_name='用户身份')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('remain_time', models.IntegerField(verbose_name='剩余时长')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('login_times', models.IntegerField(verbose_name='累计登录次数')),
                ('last_login_ip', models.CharField(max_length=20, verbose_name='最后登录ip')),
                ('last_login_time', models.DateTimeField(verbose_name='最后登录时间')),
                ('last_logout_time', models.DateTimeField(verbose_name='最后断开时间')),
                ('free_chances', models.BooleanField(default=True, verbose_name='免费权限是否已经使用')),
            ],
        ),
        migrations.AddField(
            model_name='connect',
            name='qq_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifi.User', verbose_name='用户表'),
        ),
        migrations.AddField(
            model_name='connect',
            name='tea_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wifi.Account', verbose_name='账号表'),
        ),
    ]
