# Generated by Django 2.1.1 on 2018-10-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remain_time',
            field=models.IntegerField(default=0, verbose_name='剩余时长'),
        ),
    ]
