# Generated by Django 2.1.1 on 2018-10-12 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0002_auto_20181011_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='logout_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='退出时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(default='', max_length=20, verbose_name='最后登录ip'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_logout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后断开时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_times',
            field=models.IntegerField(default=0, verbose_name='累计登录次数'),
        ),
    ]
