# Generated by Django 2.1.1 on 2018-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0003_auto_20181012_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_account',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='最后登录使用账号'),
        ),
    ]
