# Generated by Django 2.1.1 on 2018-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0004_user_last_login_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退出时间'),
        ),
    ]
