# Generated by Django 2.1.1 on 2018-10-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0005_auto_20181012_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accumulated_recharge',
            field=models.FloatField(default=0, null=True, verbose_name='累计充值金额'),
        ),
        migrations.AddField(
            model_name='user',
            name='newest_recharge',
            field=models.FloatField(null=True, verbose_name='上次充值金额'),
        ),
    ]
