# Generated by Django 2.1.1 on 2018-10-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0007_auto_20181013_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.IntegerField(choices=[(0, '超级用户'), (1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], default=1, verbose_name='用户身份'),
        ),
    ]
