# Generated by Django 2.1.1 on 2018-10-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0008_auto_20181013_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='是否禁用'),
        ),
    ]
