# Generated by Django 2.1 on 2018-08-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('account', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='账号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=8, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, default='', null=True, verbose_name='年龄')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('encode_pwd', models.CharField(max_length=32, verbose_name='加密密码')),
                ('is_useful', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_consume', models.BooleanField(default=False, verbose_name='是否被分配使用')),
                ('dept', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='所属学院部门')),
                ('position', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='职位')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
